apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasker-redis
  labels:
    app: tasker-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasker-redis
  template:
    metadata:
      labels:
        app: tasker-redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
