apiVersion: v1
kind: Service
metadata:
  name: tasker-api-service
spec:
  selector:
    app: tasker-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
  type: NodePort
