volumes:
  redis-data:
    driver: local

services:
  tasker-api:
    build: ../../api
    container_name: tasker-api
    ports:
      - "5000:5000"
    environment:
      - PORT=${PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - tasker-redis
  tasker-web:
    build: ../../web
    container_name: tasker-web
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    depends_on:
      - tasker-api
  tasker-redis:
    image: redis:6
    container_name: tasker-redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
  tasker-worker:
    build: ../../api
    command: npm run worker
    deploy:
      mode: replicated
      replicas: 3
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - tasker-redis
      - tasker-api
