apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasker-web-deployment
  labels:
    app: tasker-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasker-web
  template:
    metadata:
      labels:
        app: tasker-web
    spec:
      containers:
        - name: tasker-web-container
          image: docker-tasker-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: tasker-web-config
