apiVersion: v1
kind: Service
metadata:
  name: tasker-web-service
spec:
  selector:
    app: tasker-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30002
  type: NodePort
